name: Greet New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Thanks for opening your first issue in EcoCode! 
          
          We appreciate you taking the time to contribute to making software development more sustainable. 🌱
          
          A maintainer will review your issue soon. In the meantime, please make sure you've provided all the necessary information.
          
        pr-message: |
          🎉 Congratulations on your first pull request to EcoCode!
          
          Thank you for contributing to a more sustainable future! 🌿
          
          A maintainer will review your PR soon. Please make sure:
          - [ ] All tests pass
          - [ ] Code follows our style guidelines
          - [ ] Documentation is updated if needed
          
          Check out our [Contributing Guide](./CONTRIBUTING.md) for more information.
